name: Context

run-name: DEBUG | ${{inputs.debug}}

on:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - run: exit 1
 test:
  needs: build
  runs-on: ubuntu-latest
  steps:
   - run: echo"test"
 deploy:
  needs: [ build , test] 
  runs-on: ubuntu-latest
  steps:
   - run: echo"deploy"
  
  
