name: First Workflow 

on: 
##[push,pull_request,issues, workflow_dispatch,pull_request_review, fork]
 workflow_dispatch

jobs:
 job1:
  runs-on: self-hosted
  steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v5.0.0
     with:
      java-version: 17
      distribution: microsoft
      

